package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * Extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem for
 * use in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator:
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {

  private static final double kSimLoopPeriod = 0.004; // 4 ms

  private Notifier m_simNotifier = null;
  private double   m_lastSimTime;

  // Blue alliance: forward = 0° (toward red wall).
  private static final Rotation2d kBlueAlliancePerspective = Rotation2d.kZero;
  // Red alliance: forward = 180° (toward blue wall).
  private static final Rotation2d kRedAlliancePerspective  = Rotation2d.k180deg;

  // Tracks whether the operator perspective has been applied at least once.
  private boolean m_hasAppliedOperatorPerspective = false;

  // SysId characterization requests.
  private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
      new SwerveRequest.SysIdSwerveTranslation();
  private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
      new SwerveRequest.SysIdSwerveSteerGains();
  private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
      new SwerveRequest.SysIdSwerveRotation();

  // SysId routine for translation  - finds PID gains for drive motors.
  private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
      new SysIdRoutine.Config(
          null,          // default ramp rate (1 V/s)
          Volts.of(4),   // 4 V dynamic step to prevent brownout
          null,          // default timeout (10 s)
          state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
      new SysIdRoutine.Mechanism(
          output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

  // SysId routine for steer  - finds PID gains for steer motors.
  @SuppressWarnings("unused")
  private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
      new SysIdRoutine.Config(
          null,          // default ramp rate (1 V/s)
          Volts.of(7),   // 7 V dynamic step
          null,          // default timeout (10 s)
          state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
      new SysIdRoutine.Mechanism(
          volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

  // SysId routine for rotation  - finds gains for FieldCentricFacingAngle.
  // See SwerveRequest.SysIdSwerveRotation docs for SysId import instructions.
  @SuppressWarnings("unused")
  private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
      new SysIdRoutine.Config(
          // Units are rad/s² and rad/s, but SysId only accepts "volts" types.
          Volts.of(Math.PI / 6).per(Second),
          Volts.of(Math.PI),
          null,
          state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
      new SysIdRoutine.Mechanism(
          output -> {
            setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
            SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
          },
          null, this));

  // Active SysId routine  - swap to steer or rotation routine as needed.
  private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

  /**
   * @param drivetrainConstants Drivetrain-wide constants.
   * @param modules             Per-module constants.
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    if (Utils.isSimulation()) startSimThread();
  }

  /**
   * @param drivetrainConstants     Drivetrain-wide constants.
   * @param odometryUpdateFrequency Odometry loop frequency in Hz (0 = auto).
   * @param modules                 Per-module constants.
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    if (Utils.isSimulation()) startSimThread();
  }

  /**
   * @param drivetrainConstants       Drivetrain-wide constants.
   * @param odometryUpdateFrequency   Odometry loop frequency in Hz (0 = auto).
   * @param odometryStandardDeviation Odometry std dev [x, y, theta]ᵀ (m, m, rad).
   * @param visionStandardDeviation   Vision std dev   [x, y, theta]ᵀ (m, m, rad).
   * @param modules                   Per-module constants.
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency,
        odometryStandardDeviation, visionStandardDeviation, modules);
    if (Utils.isSimulation()) startSimThread();
  }

  /** Returns a command that applies the given swerve request each loop. */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /** Runs the SysId quasistatic test in the given direction. */
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  /** Runs the SysId dynamic test in the given direction. */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.dynamic(direction);
  }

  @Override
  public void periodic() {
    // Apply the operator perspective when first available and on every disable
    // event, so the heading is corrected if the code restarts mid-match.
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance().ifPresent(allianceColor -> {
        setOperatorPerspectiveForward(
            allianceColor == Alliance.Red
                ? kRedAlliancePerspective
                : kBlueAlliancePerspective);
        m_hasAppliedOperatorPerspective = true;
      });
    }
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();
    // Run simulation faster than the main loop so PID gains behave realistically.
    m_simNotifier = new Notifier(() -> {
      final double currentTime = Utils.getCurrentTimeSeconds();
      double deltaTime = currentTime - m_lastSimTime;
      m_lastSimTime = currentTime;
      updateSimState(deltaTime, RobotController.getBatteryVoltage());
    });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  /**
   * Adds a vision measurement to the Kalman Filter, correcting odometry while
   * accounting for measurement noise.
   *
   * @param visionRobotPoseMeters Vision-estimated robot pose.
   * @param timestampSeconds      Timestamp of the measurement in seconds.
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Adds a vision measurement with explicit standard deviations. The provided
   * deviations apply to all future measurements until changed.
   *
   * @param visionRobotPoseMeters    Vision-estimated robot pose.
   * @param timestampSeconds         Timestamp in seconds.
   * @param visionMeasurementStdDevs Std devs [x, y, theta]ᵀ (m, m, rad).
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters,
      double timestampSeconds,
      Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(visionRobotPoseMeters,
        Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }

  /**
   * Returns the robot pose at the given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds Timestamp in seconds.
   * @return Pose at that timestamp, or empty if the buffer is empty.
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }
}
